vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        spa_images:
            uri_prefix: /images/spa/room
            upload_destination: '%kernel.project_dir%/public/images/spa/room'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
